swagger: '2.0'
info:
  title: Automatized Innova C-14 Incubator API
  version: "0.1"
  description: API to execute operations on incubator
consumes:
  - application/json
produces:
  - application/json
paths:
  /status:
    get:
      tags: [status]
      operationId: incubator.status
      summary: Queries for status
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached

  /is_ready:
    get:
      tags: [is_ready]
      operationId: incubator.is_ready
      summary: Queries for ready status
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached
  /start:
    get:
      tags: [start]
      operationId: incubator.open
      summary: Opens incubator door
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached

  /stop:
    get:
      tags: [stop]
      operationId: incubator.close
      summary: Closes incubator door
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached


# no parameters for shaker
# parameters:

definitions:
  RobotResponse:
    type: object
    required:
      - status
      - value
      - details
    properties:
      status:
        type: string
        description: The response status code as a short text
        example: "OK"
        minLength: 1
      value:
        type: string
        description: The response value
        example: "204 rpm"
        minLength: 1
      details:
        type: string
        description: Complete backend stdoutput/stderror from command
        example: "Stack-trace...:"
        readOnly: true